Urdms.Dmp/Urdms.Dmp/Controllers/DmpController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Curtin.Framework.Common.UserService;
using Elmah.Contrib.Mvc;
using Urdms.Dmp.Controllers.Filters;
using Urdms.Dmp.Controllers.Helpers;
using Urdms.Dmp.Database.Entities;
using Urdms.Dmp.Database.Repositories;
using Urdms.Dmp.Mappers;
using Urdms.Dmp.Models;
using Urdms.Dmp.Models.Enums;
using Urdms.Dmp.Utils;

namespace Urdms.Dmp.Controllers
{
    [ElmahHandleError]
    public class DmpController : BaseController
    {
        private readonly NavigationButton _navigationText;
        private readonly IProjectRepository _projectRepository;
        private readonly ITimerRepository _timerRepository;

        public const int MaxStep = 5;
        public const int UserManagementStep = 4;
        public DmpController(ICurtinUserService lookupService, IProjectRepository projectRepository, ITimerRepository timerRepository)
            : base(lookupService)
        {
            _projectRepository = projectRepository;
            _timerRepository = timerRepository;
            _navigationText = new NavigationButton();
            ViewBag.NavigationButton = _navigationText;
        }

        [ProvideDataManagementPlanSteps]
        public ActionResult New(int id)
        {
            try
            {
                var project = _projectRepository.Get(id);

                if (project == null)
                {
                    return View("ProjectNotFound");
                }
                if (project.SourceProjectType == SourceProjectType.DEPOSIT)
                {
                    return View("IncorrectProjectType");
                }
                if (!this.CurrentUser.IsPrincipalInvestigatorFor(project))
                {
                    return View("NoProjectAccessRight");
                }
                // project already exists, so no creation done
                // redirect to edit
                if (project.DataManagementPlan != null)
                {
                    return RedirectToAction("Edit", new { id = project.DataManagementPlan.Id, step = 1 });
                }
                project.DataManagementPlan = new DataManagementPlan();
              
                _projectRepository.Save(project);
                // redirect to edit now that the item has been created
                return RedirectToAction("Edit", new { id = project.DataManagementPlan.Id, step = 1 });


            }
            catch
            {
                return View("Error");
            }
        }

        [HttpGet]
        [ProvideDataManagementPlanSteps]
        public ActionResult Edit(int id, int step = 1)
        {
            var project = _projectRepository.GetByDataManagementPlanId(id);
            if (project == null)
            {
                return View("DmpNotFound");
            }
            if (!this.CurrentUser.IsPrincipalInvestigatorFor(project))
            {
                return View("NoProjectAccessRight");
            }
            if (step < 1 || step > MaxStep)
            {
                return View("PageNotFound");
            }

            var viewName = string.Format("Step{0}", step);
            // note that the view model for gets are fully instantiated and populated and
            // receives all information from the entity via mapping
            var vm = ProjectViewModel.NewFullViewModel();
            vm.DataManagementPlan.Step = step;
            vm.MapFrom(project);

            vm.DataManagementPlan.Start = DateTime.Now;

            return View(viewName, vm.DataManagementPlan);
        }

        [HttpPost]
        [ProvideDataManagementPlanSteps]
		[DenyMethodByParameter(Name = "AddUrdmsUser,AddNonUrdmsUser,DeleteUrdmsUser,DeleteNonUrdmsUser,Confirm")]
        public ActionResult Edit(DataManagementPlanViewModel vm)
        {
            var project = _projectRepository.GetByDataManagementPlanId(vm.Id);
            if (project == null)
            {
                return View("DmpNotFound");
            }
            if (!this.CurrentUser.IsPrincipalInvestigatorFor(project))
            {
                return View("NoProjectAccessRight");
            }
            if (vm.Step < 1 || vm.Step > MaxStep)
            {
                return View("PageNotFound");
            }
            if (!ModelState.IsValid)
            {
                return View(string.Format("Step{0}", vm.Step), vm);
            }
            var currentStep = vm.Step;
            vm.Step = GetStep(vm.Step);

            var projectModel = new ProjectViewModel { DataManagementPlan = vm };
            // Copy project details from project entity
            projectModel.MapFrom(project, false);
            // delete users when in the appropriate step
            project.MapFrom(projectModel, currentStep == UserManagementStep);
            var urdmsUsers = project.Parties.Where(o => !string.IsNullOrWhiteSpace(o.Party.UserId) && o.Party.Id == 0).Select(o => o.Party);
            // only update new parties
            this.UpdateUrdmsPartyDetails(urdmsUsers.ToList());

            _projectRepository.Save(project);

            //Dmp form completion timer for steps 1-4. Only on next button submit.
            if (currentStep < vm.Step)
            {
                _timerRepository.Save(new FormTimer
                                          {
                                              UserId = CurrentUser.CurtinId,
                                              EndTime = DateTime.Now,
                                              Id = vm.Id,
                                              StartTime = vm.Start,
                                              Step = vm.Step - 1
                                          });
            }

            return RedirectToAction("Edit", new { id = vm.Id, step = vm.Step });
        }


        [HttpPost]
        [ProvideDataManagementPlanSteps]
        [AcceptMethodByParameter(Name = "AddUrdmsUser")]
        [ActionName("Edit")]
        public ActionResult AddUrdmsUser(DataManagementPlanViewModel vm)
        {
            if (!string.IsNullOrWhiteSpace(vm.FindUserId))
            {
                var urdmsUser = GetUser(vm.FindUserId.Trim());
                if (urdmsUser != null)
                {
                    var project = _projectRepository.GetByDataManagementPlanId(vm.Id);

                    vm.AddUrdmsUser(urdmsUser, AccessRole.Members);

                    var entityUser = project.Parties
                        .Where(user => string.Compare(user.Party.UserId, urdmsUser.CurtinId, true) == 0)
                        .Take(1)
                        .FirstOrDefault();

                    var modelUser = vm.UrdmsUsers
                        .Where(user => string.Compare(user.UserId, urdmsUser.CurtinId, true) == 0)
                        .Take(1)
                        .FirstOrDefault();

                    if (entityUser != null && modelUser != null)
                    {
                        modelUser.Id = entityUser.Id;
                        modelUser.PartyId = entityUser.Party.Id;
                    }

                }

                vm.FindUserId = null;
            }

            var viewName = string.Format("Step{0}", vm.Step);
            return View(viewName, vm);
        }

        [HttpPost]
        [ProvideDataManagementPlanSteps]
        [AcceptMethodByParameter(Name = "AddNonUrdmsUser")]
        [ActionName("Edit")]
		public ActionResult AddNonUrdmsUser(DataManagementPlanViewModel vm)
        {
            if (!string.IsNullOrWhiteSpace(vm.NonUrdmsNewUserName))
            {
                var project = _projectRepository.GetByDataManagementPlanId(vm.Id);
                vm.AddNonUrdmsUser(vm.NonUrdmsNewUserName.Trim(), AccessRole.Visitors);

                var entityUser = project.Parties
                        .Where(user => string.Compare(user.Party.FullName.Trim(), vm.NonUrdmsNewUserName.Trim(), true) == 0)
                        .Take(1)
                        .FirstOrDefault();
                var modelUser = vm.NonUrdmsUsers
                    .Where(user => string.Compare(user.FullName.Trim(), vm.NonUrdmsNewUserName.Trim(), true) == 0)
                    .Take(1)
                    .FirstOrDefault();
                if (entityUser != null && modelUser != null)
                {
                    modelUser.Id = entityUser.Party.Id;
                }
                vm.NonUrdmsNewUserName = null;
            }
            var viewName = string.Format("Step{0}", vm.Step);
            return View(viewName, vm);
        }

        [HttpPost]
        [ProvideDataManagementPlanSteps]
		[AcceptMethodByParameter(Name = "DeleteUrdmsUser")]
        [ActionName("Edit")]
		public ActionResult RemoveUrdmsUser(DataManagementPlanViewModel vm)
        {
            var viewName = string.Format("Step{0}", vm.Step);
            return View(viewName, vm);
        }

        [HttpPost]
        [ProvideDataManagementPlanSteps]
        [AcceptMethodByParameter(Name = "DeleteNonUrdmsUser")]
        [ActionName("Edit")]
		public ActionResult RemoveNonUrdmsUser(DataManagementPlanViewModel vm)
        {
            var viewName = string.Format("Step{0}", vm.Step);
            return View(viewName, vm);
        }

        [HttpPost]
        [AcceptMethodByParameter(Name = "Confirm")]
        [ActionName("Edit")]
        public ActionResult Confirm(DataManagementPlanViewModel vm)
        {
            var project = _projectRepository.GetByDataManagementPlanId(vm.Id);
            if (project == null)
            {
                return View("ProjectNotFound");
            }
            if (!this.CurrentUser.IsPrincipalInvestigatorFor(project))
            {

Urdms.Dmp/Urdms.Dmp/Views/Confirm/Pending.cshtml
@model Urdms.Dmp.Models.DataManagementPlanInfoViewModel
@{
    Helper.FlowFormCssAndJs(this);
}
@helper ConfirmationInstructions()
    {
    <span style="font-style: normal;">Your request for the creation of a Project Storage
        Space for this research project is in progress. You will be notified by email upon
        successful creation of the Project Storage Space. You will have the ability
        to update the PDF of the Data Management Plan as soon as you get access to the Project
        Storage Space.</span>
}
@using (var f = Html.BeginFlowForm())
{
    @Html.HiddenFor(m => m.DataManagementPlanId)
    @Html.HiddenFor(m => m.ProjectTitle)
    @f.Steps(ViewBag.Steps, 6, 6, true, true)
    @f.Header("Data Management Review")
    <h2>Data Management Plan for: <strong>@Model.ProjectTitle</strong></h2>
    using (var s = f.BeginSection("Provisioning In Progress", "inprogress"))
    {
    <label>@ConfirmationInstructions()</label>
    }

    using (var n = f.BeginNavigation())
    {
    @n.Submit("Previous", name: "Previous", id: "Previous")
    }

    @f.Footer(area: "", id: "XXXXX", date: "2011-08-16")
}

Urdms.Dmp/Urdms.Dmp/Views/Confirm/Republish.cshtml
@model Urdms.Dmp.Models.DataManagementPlanInfoViewModel
@{
    Helper.FlowFormCssAndJs(this);
}
@helper ConfirmationInstructions()
    {
    <span style="font-style: normal;">Click the Update button below to create a new PDF
        copy of the Data Management Plan. The PDF file will be saved in the admin section
        of the Project Storage Space. Please visit the Project Storage Space to
        access the PDF.</span>
}
@using (var f = Html.BeginFlowForm())
{
    @Html.HiddenFor(m => m.ProjectId)
    @Html.HiddenFor(m => m.DataManagementPlanId)
    @Html.HiddenFor(m => m.ProjectTitle)

    @f.Steps(ViewBag.Steps, 6, 6, true, true)
    @f.Header("Data Management Review")
    <h2>Data Management Plan for: <strong>@Model.ProjectTitle</strong></h2>
    using (var s = f.BeginSection("Update", "republish"))
    {
    <label>@ConfirmationInstructions()</label>
    }

    using (var n = f.BeginNavigation())
    {
    @n.Submit("Previous", name: "Previous", id: "Previous")
    @n.Submit("Update", name: "Republish", id: "Republish")
    }

    @f.Footer(area: "", id: "XXXXX", date: "2011-08-16")
}

Urdms.Dmp/Urdms.Dmp/Views/Confirm/Republished.cshtml
@{
    Helper.FlowFormCssAndJs(this);
    ViewBag.Title = "Thank you";
}
@using (var f = Html.BeginFlowForm())
{
    @f.Steps(ViewBag.Steps, 6, 6, true, true)
    <div class="confirmation_message">
        <h2>Thank you</h2>
        <div class="message">
            <p>Thank you for updating your Data Management Plan. A new PDF copy of your Data Management
                Plan will be deposited in the in the admin section of the Project Storage Space.</p>
        </div>
    </div>
}

Urdms.Dmp/Urdms.Dmp/Views/Confirm/Review.cshtml
@model Urdms.Dmp.Models.ConfirmDataManagementPlanViewModel
@{
    Helper.FlowFormCssAndJs(this);
}
@helper ConfirmationInstructions()
    {
    <span style="font-style: normal;">I acknowledge that by submitting the Data Management
        Plan I will gain access to the Project Storage Space for <em>"@Model.ProjectTitle"</em>.
        Researchers or project members identified in sub-section Access, of
        @Html.ActionLink("section 4", "Edit", "Dmp", new { id = Model.DataManagementPlanId, step = 5 }, new { })
        will also be given access to the Project Storage Space as per their respective roles.</span>
}
@using (var f = Html.BeginFlowForm())
{
    @Html.HiddenFor(m => m.DataManagementPlanId)
    @Html.HiddenFor(m => m.ProjectTitle)
    @f.Steps(ViewBag.Steps, 6, 6, true, true)
    @f.Header("Data Management Review")
    <h2>Data Management Plan for: <strong>@Model.ProjectTitle</strong></h2>
    using (var s = f.BeginSection("Confirm", "confirm"))
    {
    <dt></dt>
    <dd @if (ViewContext.ViewData.ModelState.Keys.Contains("HasConfirmed") && ViewContext.ViewData.ModelState["HasConfirmed"].Errors.Count > 0)
        { <text>class="invalid"</text> } >@Html.ValidationMessageFor(x => x.HasConfirmed, null, new { @class = "invalid-message" })
        <label>@Html.CheckBoxFor(x => x.HasConfirmed) @ConfirmationInstructions()</label></dd>
    }

    <div class="container">
        @using (var n = f.BeginNavigation())
        {
            @n.Submit("Previous", name: "Previous", id: "Previous", classes: "float-left")
            @n.Submit("Submit", name: "Submit", id: "Submit", classes: "float-right")
        }
    </div>

    @f.Footer(area: "", id: "XXXXX", date: "2011-08-16")
}

Urdms.Dmp/Urdms.Dmp/Views/Confirm/ReviewDataDeposit.cshtml
@model Urdms.Dmp.Models.ConfirmDataDepositViewModel
@{
    Helper.FlowFormCssAndJs(this);
}
@helper ConfirmationInstructions()
    {
    <span style="font-style: normal;">I acknowledge that by submitting the Data Management
        Plan I will gain access to the Project Storage Space for <em>"@Model.ProjectTitle"</em>.
        Researchers or project members identified in Data Deposit form will also
        be given access to the Project Storage Space as per their respective roles.</span>
}
@using (var f = Html.BeginFlowForm())
{
    @Html.HiddenFor(m => m.ProjectId)
    @Html.HiddenFor(m => m.ProjectTitle)
    @f.Header("Data Deposit Form Review")
    <h2>Data Management Plan for: <strong>@Model.ProjectTitle</strong></h2>
    using (var s = f.BeginSection("Confirm", "confirm"))
    {
    <dt></dt>
    <dd @if (ViewContext.ViewData.ModelState.Keys.Contains("HasConfirmed") && ViewContext.ViewData.ModelState["HasConfirmed"].Errors.Count > 0)
        { <text>class="invalid"</text> } >@Html.ValidationMessageFor(x => x.HasConfirmed, null, new { @class = "invalid-message" })
        <label>@Html.CheckBoxFor(x => x.HasConfirmed) @ConfirmationInstructions()</label></dd>
    }

    using (var n = f.BeginNavigation())
    {
    @n.Submit("Submit", name: "Submit", id: "Submit")
    }

    @f.Footer(area: "", id: "XXXXX", date: "2011-08-16")
}

Urdms.Dmp/Urdms.Dmp/Views/Confirm/Submitted.cshtml
@model Urdms.Dmp.Database.Entities.Project
@{
    Helper.FlowFormCssAndJs(this);
    ViewBag.Title = "Thank you";
}
@using (var f = Html.BeginFlowForm())
{
    @f.Steps(ViewBag.Steps, 6, 6, true, true)
    <div class="confirmation_message">
        <h2>Thank you</h2>
        <div class="message">
			<p>Thank you for submitting your Data Management Plan for <em>@Model.Title</em>.</p>
            <p>Your Project Storage Space ID is: @Model.Id</p>
        </div>
    </div>
}

Urdms.Dmp/Urdms.Dmp/Views/Confirm/SubmittedDataDeposit.cshtml
@model Urdms.Dmp.Database.Entities.Project
@{
    Helper.FlowFormCssAndJs(this);
    ViewBag.Title = "Thank you";
}

@using (var f = Html.BeginFlowForm())
{
    <div class="confirmation_message">
        <h2>Thank you</h2>
        <div class="message">
			<p>Thank you for submitting your Data Deposit form for <em>@Model.Title</em>.</p>
            <p>YourProject Storage Space ID is: @Model.Id</p>
        </div>
    </div>
}